version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "npm v$(npm -v)"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      # - run:
      #     name: Test
      #     command: yarn test
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/repo/.nuxt/dist
            - ~/repo/node_modules
            - ~/repo/package.json

  deploy:
    working_directory: ~/repo
    docker:
      - image: google/cloud-sdk

    steps:
      - checkout
      - restore_cache:
          key: cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Deploy to Google App Engine
          command: |
            echo "$GOOGLE_AUTH" | base64 -i --decode > "$HOME/gcp-key.json"
            gcloud auth activate-service-account --key-file "$HOME/gcp-key.json"
            gcloud --quiet config set project "$GOOGLE_PROJECT_ID"
            gcloud --quiet app deploy app.yaml --version $(echo $CIRCLE_BRANCH | sed "s/\//\-/g")
          no_output_timeout: 20m

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

